version: '3.3'

services:

  wordpress:
    build:                   ./docker_wordpress
    depends_on:
    - mysql
    container_name:          grp5-wp
    environment:
      WORDPRESS_DB_USER:     ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      VIRTUAL_HOST:          ${DOMAINS}
      LETSENCRYPT_HOST:      ${DOMAINS}
      LETSENCRYPT_EMAIL:     ${EMAIL}
#    Volumes pour wp-content uniquement ou pour tous les fichiers (tests)
#    volumes:
#    - ./wp_files/wp-content:/var/www/html/wp-content
#    - ./docker_wordpress/wp_files:/var/www/html

  phpmyadmin:
    image:                 phpmyadmin/phpmyadmin
    restart:               always
    container_name:        grp5-pma
    environment:
      PMA_ARBITRARY:       1
      PMA_HOST:            mysql
      PMA_PORT:            3306
      VIRTUAL_HOST:        ${PHPMYADMINDOMAINS}
      LETSENCRYPT_HOST:    ${PHPMYADMINDOMAINS}
      LETSENCRYPT_EMAIL:   ${EMAIL}
    volumes:
    - /sessions
    depends_on:
    - mysql

  mysql:
    image: mysql:5.7
    container_name:        grp5-mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE:      $DB_DATABASE
      MYSQL_USER:          $DB_USER
      MYSQL_PASSWORD:      $DB_PASSWORD
    command:               ["bash", "-c", 'docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci']
    volumes:
    - /var/lib/mysql
    - ./docker_mysql/db_wp_chanter.sql:/docker-entrypoint-initdb.d/db.sql

networks:
  default:
    external:
      name:                ${NETWORK}
